### ISSUE TITLE
dll in system 32 folder... correct reg files?

### ISSUE THREAD

**Issue by gabri25ele** [NoDrawFocusRectW11/NoDrawFocusRectW11#1]
in new instruction you say

    Copy x64\Release\NoDrawFocusRectW11.dll to C:\Windows\System32
    Run install-x64.reg

but in install-x64.reg, there is no reference to syswow64 folder?
If we copy to C:\Windows\System32, the correct reg to run should be this?

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows]
"LoadAppInit_DLLs"=dword:00000001
"AppInit_DLLs"="NoDrawFocusRectW11.dll"

**Comment by NoDrawFocusRectW11** [comment]
Looks like you are correct, the .reg files reference the opposite folders. Those were unmodified from the project I copied from. I'll double check this and change their names. Thank you.

**Comment by NoDrawFocusRectW11** [comment]
Thank you, I have modified the file names. In my very limited testing it seems to be correct, so I am closing this ticket. 

Please let me know if there is still something wrong
