### ISSUE TITLE
Unable to use this in Windows 11.

### ISSUE THREAD

**Issue by rkoharchik** [NoDrawFocusRectW11/NoDrawFocusRectW11#4]
Secure boot seems to prevent this from working, and if secure boot is turned off, the Windows 11 crashes upon launch.

**Comment by ItsProfessional** [comment]
I have ported this mod to Windhawk, which uses a better dll injection mechanism which works even with secure boot enabled.
https://windhawk.net/mods/no-focus-rectangle

**Comment by rkoharchik** [comment]
You are the absolute best! Finally after all these years, a working solution!!
